#!/bin/bash
# 手动浏览器验证指南

echo "=== Stepper 组件验证指南 ==="
echo ""
echo "Web 服务已在 http://localhost:5173 启动"
echo ""
echo "请在浏览器中打开以下 URL 进行验证："
echo "  http://localhost:5173/setup"
echo ""
echo "=== 验证检查清单 ==="
echo ""
echo "1. 页面结构验证："
echo "   [ ] 页面标题「一键配置向导」存在"
echo "   [ ] 第一个卡片是「1. 选择输入模式」"
echo "   [ ] 初始状态下没有 Stepper（因为 runDetail 为空）"
echo ""
echo "2. 触发 Stepper 显示："
echo "   [ ] 填写 Quick 模式表单（配置名称、项目 key、仓库路径等）"
echo "   [ ] 点击「确认并一键配置」按钮"
echo "   [ ] 等待执行开始"
echo ""
echo "3. Stepper 位置验证："
echo "   [ ] Stepper 出现在页面标题下方"
echo "   [ ] Stepper 在所有卡片（1/2/3）之前"
echo "   [ ] Stepper 容器有渐变背景和视觉增强效果"
echo "   [ ] 容器内显示「执行步骤」标题和进度百分比"
echo ""
echo "4. 动画效果验证："
echo "   [ ] 当前步骤（current）有明显的脉冲动画和扩散环"
echo "   [ ] 步骤完成时（completed）有弹簧 pop 动画和勾选图标描边动画"
echo "   [ ] 步骤失败时（failed）有抖动和红色光晕"
echo "   [ ] 连接线有方向性填充动画（横向左→右，纵向上→下）"
echo ""
echo "5. 响应式验证："
echo "   [ ] 桌面宽度（>768px）：Stepper 横向排列"
echo "   [ ] 移动宽度（<768px）：Stepper 纵向排列"
echo "   [ ] 调整浏览器宽度时布局正确切换"
echo ""
echo "6. 无重复验证："
echo "   [ ] 旧的「4. 执行进度」卡片内不再有 Stepper"
echo "   [ ] 页面上只有一个 Stepper 实例（在顶部）"
echo ""
echo "7. SSE 实时更新验证："
echo "   [ ] 步骤状态变化时动画正确触发"
echo "   [ ] 进度百分比实时更新"
echo "   [ ] 当前步骤卡片内容同步更新"
echo ""
echo "=== 快速验证命令 ==="
echo ""
echo "在浏览器开发者工具 Console 中运行："
echo ""
echo "// 检查顶部 Stepper 容器"
echo "document.querySelector('div:has(> div > div:has-text(\"执行步骤\"))')"
echo ""
echo "// 检查是否有重复 Stepper"
echo "document.querySelectorAll('[class*=\"flex items-center\"]').length"
echo ""
echo "=== 截图建议 ==="
echo ""
echo "1. 初始状态（无 Stepper）"
echo "2. 执行开始后（Stepper 在顶部）"
echo "3. 桌面宽度视图"
echo "4. 移动宽度视图"
echo "5. 步骤切换动画过程"
echo ""
