"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExecutorOverrideSchema = exports.ExecutorInstanceSchema = exports.ExecutorTypeEnum = exports.DispatchStatus = exports.WorkerStatus = exports.getErrorMessage = exports.getApprovalPolicyService = exports.extractRepoName = exports.resolveUserPath = exports.validateRemoteUrl = exports.cloneRepository = exports.getGitRepoSummary = exports.getGitRepoInfo = exports.isGitRepository = exports.checkGitInstalled = exports.validateEditableSimpleManifest = exports.validateSimpleManifest = exports.detectManifestType = exports.loadEditableSimpleManifest = exports.loadManifest = exports.createLogger = exports.LogLevel = exports.Logger = exports.validateConfig = exports.getEnvArray = exports.getEnvBoolean = exports.getEnvNumber = exports.getEnvString = exports.convertSimpleToFullManifest = exports.EditableSimpleManifestSchema = exports.SimpleManifestSchema = exports.DeploySchema = exports.NotifySchema = exports.OpenClawSchema = exports.ManifestSchema = exports.MemorySchema = exports.PromptDraftVersionSchema = exports.FallbackConfigSchema = exports.PromptEngineSchema = exports.ConnectModeSchema = exports.WorkersSchema = exports.WorkerSchema = exports.OpenCodeConfigSchema = exports.ProjectSchema = exports.SshNodeSchema = exports.LocalNodeSchema = exports.NodesSchema = exports.NodeSchema = exports.ControllerSchema = exports.ProfileSchema = void 0;
exports.ControllerErrorCode = exports.TaskPriority = exports.ApprovalAction = exports.TaskStatus = exports.StepType = exports.CheckStatus = exports.formatValidationIssue = exports.detectManifestVersion = exports.convertV1ToV2 = exports.WorkersV2Schema = exports.WorkerV2Schema = exports.ProjectV2Schema = exports.TriggersSchema = exports.TriggerInstanceSchema = exports.TriggerTypeEnum = exports.ExecutorsSchema = void 0;
// ============ Schema 导出 ============
var profile_1 = require("./schema/profile");
Object.defineProperty(exports, "ProfileSchema", { enumerable: true, get: function () { return profile_1.ProfileSchema; } });
var controller_1 = require("./schema/controller");
Object.defineProperty(exports, "ControllerSchema", { enumerable: true, get: function () { return controller_1.ControllerSchema; } });
var node_1 = require("./schema/node");
Object.defineProperty(exports, "NodeSchema", { enumerable: true, get: function () { return node_1.NodeSchema; } });
Object.defineProperty(exports, "NodesSchema", { enumerable: true, get: function () { return node_1.NodesSchema; } });
Object.defineProperty(exports, "LocalNodeSchema", { enumerable: true, get: function () { return node_1.LocalNodeSchema; } });
Object.defineProperty(exports, "SshNodeSchema", { enumerable: true, get: function () { return node_1.SshNodeSchema; } });
var project_1 = require("./schema/project");
Object.defineProperty(exports, "ProjectSchema", { enumerable: true, get: function () { return project_1.ProjectSchema; } });
Object.defineProperty(exports, "OpenCodeConfigSchema", { enumerable: true, get: function () { return project_1.OpenCodeConfigSchema; } });
var worker_1 = require("./schema/worker");
Object.defineProperty(exports, "WorkerSchema", { enumerable: true, get: function () { return worker_1.WorkerSchema; } });
Object.defineProperty(exports, "WorkersSchema", { enumerable: true, get: function () { return worker_1.WorkersSchema; } });
Object.defineProperty(exports, "ConnectModeSchema", { enumerable: true, get: function () { return worker_1.ConnectModeSchema; } });
var prompt_engine_1 = require("./schema/prompt-engine");
Object.defineProperty(exports, "PromptEngineSchema", { enumerable: true, get: function () { return prompt_engine_1.PromptEngineSchema; } });
Object.defineProperty(exports, "FallbackConfigSchema", { enumerable: true, get: function () { return prompt_engine_1.FallbackConfigSchema; } });
var prompt_draft_1 = require("./schema/prompt-draft");
Object.defineProperty(exports, "PromptDraftVersionSchema", { enumerable: true, get: function () { return prompt_draft_1.PromptDraftVersionSchema; } });
var memory_1 = require("./schema/memory");
Object.defineProperty(exports, "MemorySchema", { enumerable: true, get: function () { return memory_1.MemorySchema; } });
var manifest_1 = require("./schema/manifest");
Object.defineProperty(exports, "ManifestSchema", { enumerable: true, get: function () { return manifest_1.ManifestSchema; } });
Object.defineProperty(exports, "OpenClawSchema", { enumerable: true, get: function () { return manifest_1.OpenClawSchema; } });
Object.defineProperty(exports, "NotifySchema", { enumerable: true, get: function () { return manifest_1.NotifySchema; } });
Object.defineProperty(exports, "DeploySchema", { enumerable: true, get: function () { return manifest_1.DeploySchema; } });
var manifest_simple_1 = require("./schema/manifest-simple");
Object.defineProperty(exports, "SimpleManifestSchema", { enumerable: true, get: function () { return manifest_simple_1.SimpleManifestSchema; } });
Object.defineProperty(exports, "EditableSimpleManifestSchema", { enumerable: true, get: function () { return manifest_simple_1.EditableSimpleManifestSchema; } });
Object.defineProperty(exports, "convertSimpleToFullManifest", { enumerable: true, get: function () { return manifest_simple_1.convertSimpleToFullManifest; } });
// ============ 配置工具导出 ============
var config_1 = require("./config");
Object.defineProperty(exports, "getEnvString", { enumerable: true, get: function () { return config_1.getEnvString; } });
Object.defineProperty(exports, "getEnvNumber", { enumerable: true, get: function () { return config_1.getEnvNumber; } });
Object.defineProperty(exports, "getEnvBoolean", { enumerable: true, get: function () { return config_1.getEnvBoolean; } });
Object.defineProperty(exports, "getEnvArray", { enumerable: true, get: function () { return config_1.getEnvArray; } });
Object.defineProperty(exports, "validateConfig", { enumerable: true, get: function () { return config_1.validateConfig; } });
// ============ 日志工具导出 ============
var logger_1 = require("./logger");
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return logger_1.Logger; } });
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return logger_1.LogLevel; } });
Object.defineProperty(exports, "createLogger", { enumerable: true, get: function () { return logger_1.createLogger; } });
// ============ Manifest 加载工具导出 ============
var manifest_loader_1 = require("./utils/manifest-loader");
Object.defineProperty(exports, "loadManifest", { enumerable: true, get: function () { return manifest_loader_1.loadManifest; } });
Object.defineProperty(exports, "loadEditableSimpleManifest", { enumerable: true, get: function () { return manifest_loader_1.loadEditableSimpleManifest; } });
Object.defineProperty(exports, "detectManifestType", { enumerable: true, get: function () { return manifest_loader_1.detectManifestType; } });
Object.defineProperty(exports, "validateSimpleManifest", { enumerable: true, get: function () { return manifest_loader_1.validateSimpleManifest; } });
Object.defineProperty(exports, "validateEditableSimpleManifest", { enumerable: true, get: function () { return manifest_loader_1.validateEditableSimpleManifest; } });
// ============ Git 工具导出 ============
var git_utils_1 = require("./utils/git-utils");
Object.defineProperty(exports, "checkGitInstalled", { enumerable: true, get: function () { return git_utils_1.checkGitInstalled; } });
Object.defineProperty(exports, "isGitRepository", { enumerable: true, get: function () { return git_utils_1.isGitRepository; } });
Object.defineProperty(exports, "getGitRepoInfo", { enumerable: true, get: function () { return git_utils_1.getGitRepoInfo; } });
Object.defineProperty(exports, "getGitRepoSummary", { enumerable: true, get: function () { return git_utils_1.getGitRepoSummary; } });
Object.defineProperty(exports, "cloneRepository", { enumerable: true, get: function () { return git_utils_1.cloneRepository; } });
Object.defineProperty(exports, "validateRemoteUrl", { enumerable: true, get: function () { return git_utils_1.validateRemoteUrl; } });
Object.defineProperty(exports, "resolveUserPath", { enumerable: true, get: function () { return git_utils_1.resolveUserPath; } });
Object.defineProperty(exports, "extractRepoName", { enumerable: true, get: function () { return git_utils_1.extractRepoName; } });
// ============ 服务导出 ============
var approval_policy_service_1 = require("./services/approval-policy-service");
Object.defineProperty(exports, "getApprovalPolicyService", { enumerable: true, get: function () { return approval_policy_service_1.getApprovalPolicyService; } });
// ============ 工具函数导出 ============
var error_messages_1 = require("./i18n/error-messages");
Object.defineProperty(exports, "getErrorMessage", { enumerable: true, get: function () { return error_messages_1.getErrorMessage; } });
var worker_record_1 = require("./types/worker-record");
Object.defineProperty(exports, "WorkerStatus", { enumerable: true, get: function () { return worker_record_1.WorkerStatus; } });
var dispatch_record_1 = require("./types/dispatch-record");
Object.defineProperty(exports, "DispatchStatus", { enumerable: true, get: function () { return dispatch_record_1.DispatchStatus; } });
// ============ V2 Manifest Schema 导出 ============
var manifest_v2_1 = require("./schema/manifest-v2");
Object.defineProperty(exports, "ExecutorTypeEnum", { enumerable: true, get: function () { return manifest_v2_1.ExecutorTypeEnum; } });
Object.defineProperty(exports, "ExecutorInstanceSchema", { enumerable: true, get: function () { return manifest_v2_1.ExecutorInstanceSchema; } });
Object.defineProperty(exports, "ExecutorOverrideSchema", { enumerable: true, get: function () { return manifest_v2_1.ExecutorOverrideSchema; } });
Object.defineProperty(exports, "ExecutorsSchema", { enumerable: true, get: function () { return manifest_v2_1.ExecutorsSchema; } });
Object.defineProperty(exports, "TriggerTypeEnum", { enumerable: true, get: function () { return manifest_v2_1.TriggerTypeEnum; } });
Object.defineProperty(exports, "TriggerInstanceSchema", { enumerable: true, get: function () { return manifest_v2_1.TriggerInstanceSchema; } });
Object.defineProperty(exports, "TriggersSchema", { enumerable: true, get: function () { return manifest_v2_1.TriggersSchema; } });
Object.defineProperty(exports, "ProjectV2Schema", { enumerable: true, get: function () { return manifest_v2_1.ProjectV2Schema; } });
Object.defineProperty(exports, "WorkerV2Schema", { enumerable: true, get: function () { return manifest_v2_1.WorkerV2Schema; } });
Object.defineProperty(exports, "WorkersV2Schema", { enumerable: true, get: function () { return manifest_v2_1.WorkersV2Schema; } });
var manifest_v2_compatibility_1 = require("./schema/manifest-v2-compatibility");
Object.defineProperty(exports, "convertV1ToV2", { enumerable: true, get: function () { return manifest_v2_compatibility_1.convertV1ToV2; } });
Object.defineProperty(exports, "detectManifestVersion", { enumerable: true, get: function () { return manifest_v2_compatibility_1.detectManifestVersion; } });
var validation_1 = require("./utils/validation");
Object.defineProperty(exports, "formatValidationIssue", { enumerable: true, get: function () { return validation_1.formatValidationIssue; } });
var doctor_1 = require("./interfaces/doctor");
Object.defineProperty(exports, "CheckStatus", { enumerable: true, get: function () { return doctor_1.CheckStatus; } });
var plan_1 = require("./interfaces/plan");
Object.defineProperty(exports, "StepType", { enumerable: true, get: function () { return plan_1.StepType; } });
var task_1 = require("./interfaces/task");
Object.defineProperty(exports, "TaskStatus", { enumerable: true, get: function () { return task_1.TaskStatus; } });
Object.defineProperty(exports, "ApprovalAction", { enumerable: true, get: function () { return task_1.ApprovalAction; } });
Object.defineProperty(exports, "TaskPriority", { enumerable: true, get: function () { return task_1.TaskPriority; } });
var errors_1 = require("./types/errors");
Object.defineProperty(exports, "ControllerErrorCode", { enumerable: true, get: function () { return errors_1.ControllerErrorCode; } });
//# sourceMappingURL=index.js.map